---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kitaame/public_html/
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R index.css $DEPLOYPATH
    - /bin/cp -R index.js $DEPLOYPATH
